In [2]:
!python -V

Python 3.5.2 :: Anaconda custom (64-bit)


In [3]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [5]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

250021.515544
Vectorized version:1.0025501251220703ms
250021.515544
For loop:493.27993392944336ms


### broadcasting
(m, n)矩阵 $+、-、*、/$ 一个(1,n)矩阵，python会将这个(1,n)矩阵复制成(m, n)矩阵

### numpy vectors

In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a) # neither a row vector nor a column vector, just a rank 1 array

[ 0.24774803  0.21885057  0.71506325  0.80313516  0.97970358]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.24774803  0.21885057  0.71506325  0.80313516  0.97970358]


In [5]:
print(a.T.shape)

(5,)


In [6]:
print(np.dot(a, a.T))

2.22543529037


In [11]:
a = np.random.randn(5, 1) # suggest type
print(a)
print(a.shape)

[[ 0.34528812]
 [-0.55700762]
 [-1.29550808]
 [ 0.44638784]
 [-1.31250885]]
(5, 1)


In [12]:
print(a.T)

[[ 0.34528812 -0.55700762 -1.29550808  0.44638784 -1.31250885]]


In [13]:
print(np.dot(a, a.T))

[[ 0.11922389 -0.19232811 -0.44732355  0.15413242 -0.45319372]
 [-0.19232811  0.31025748  0.72160787 -0.24864143  0.73107743]
 [-0.44732355  0.72160787  1.6783412  -0.57829906  1.70036583]
 [ 0.15413242 -0.24864143 -0.57829906  0.19926211 -0.585888  ]
 [-0.45319372  0.73107743  1.70036583 -0.585888    1.72267948]]


In [16]:
assert(a.shape == (5,1)) # 检查维度